/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author anuja
 */
public class AllImageDisplay extends javax.swing.JFrame {

    /**
     * Creates new form AllImageDisplay
     */
    int i=0;
    File[] allFiles;
    ImageIcon[] scaledIcon=null;
    int j;
    
    
    public AllImageDisplay() {
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathFld = new javax.swing.JTextField();
        folderChooseBtn = new javax.swing.JButton();
        imageDisplayLabel = new javax.swing.JLabel();
        firstImageBtn = new javax.swing.JButton();
        previousImageBtn = new javax.swing.JButton();
        nextImageBtn = new javax.swing.JButton();
        lastImageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        folderChooseBtn.setText("...");
        folderChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderChooseBtnActionPerformed(evt);
            }
        });

        firstImageBtn.setText("|<");
        firstImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstImageBtnActionPerformed(evt);
            }
        });

        previousImageBtn.setText("<");
        previousImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousImageBtnActionPerformed(evt);
            }
        });

        nextImageBtn.setText(">");
        nextImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextImageBtnActionPerformed(evt);
            }
        });

        lastImageBtn.setText(">|");
        lastImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastImageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pathFld, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(folderChooseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(previousImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(nextImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lastImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imageDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(folderChooseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(pathFld))
                .addGap(18, 18, 18)
                .addComponent(imageDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousImageBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextImageBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextImageBtnActionPerformed
    
        if(i!=allFiles.length-1)
        {   
                  i++;
                
                   imageDisplayLabel.setIcon(scaledIcon[i]);
        }
                
                  
    }//GEN-LAST:event_nextImageBtnActionPerformed

    private void folderChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderChooseBtnActionPerformed
        
        
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        JFileChooser chooser=new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.addChoosableFileFilter(fnef);
        chooser.showOpenDialog(null);
         File folder=chooser.getSelectedFile();
         if(folder!=null)
         {
          if(folder.isDirectory())
          {
            allFiles=folder.listFiles();
            if(folder!=null)
            {
                    String fileName=folder.getAbsolutePath();
                     pathFld.setText(fileName);


                        /* ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                         Image img=icon.getImage();
                         Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                         ImageIcon scaledIcon=new ImageIcon(imgScale);
                         imageDisplayLabel.setIcon(scaledIcon);*/

                     scaledIcon=new ImageIcon[allFiles.length];
                     for(int l=0;l<=scaledIcon.length-1;l++)
                     {
                         ImageIcon icon=new ImageIcon(allFiles[l].getAbsolutePath());
                         Image img=icon.getImage();
                         Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                         scaledIcon[l]=new ImageIcon(imgScale);

                     }
                   //  imageDisplayFile(allFiles[i]);
                      imageDisplayLabel.setIcon(scaledIcon[i]); 
                    }


               }
         }
       
        
    
        
    }//GEN-LAST:event_folderChooseBtnActionPerformed

    private void previousImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousImageBtnActionPerformed
     
        if(i!=0)
        {
              i--;
             /*ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);
                 imageDisplayLabel.setIcon(scaledIcon);*/
             // imageDisplayFile(scaledIcon[l]);
              imageDisplayLabel.setIcon(scaledIcon[i]);
             
                 
        }
      
                
       
    }//GEN-LAST:event_previousImageBtnActionPerformed

    private void lastImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastImageBtnActionPerformed
       
           /*  ImageIcon icon=new ImageIcon(allFiles[allFiles.length-1].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);
                 imageDisplayLabel.setIcon(scaledIcon);*/
        //imageDisplay(allFiles.length-1);
        imageDisplayLabel.setIcon(scaledIcon[scaledIcon.length-1]);
                  
        
    }//GEN-LAST:event_lastImageBtnActionPerformed

    private void firstImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstImageBtnActionPerformed
        
           // imageDisplay(0);
                 imageDisplayLabel.setIcon(scaledIcon[0]);  
        
    }//GEN-LAST:event_firstImageBtnActionPerformed
   public void imageDisplay(int index){
     /*   ImageIcon icon=new ImageIcon(allFiles[index].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);*/
                
                 
                
   }
   
   public void imageDisplayFile(ImageIcon f){
       /* ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);*/
                
                 //imageDisplayLabel.setIcon(scaledIcon[l]);
                 
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllImageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllImageDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstImageBtn;
    private javax.swing.JButton folderChooseBtn;
    private javax.swing.JLabel imageDisplayLabel;
    private javax.swing.JButton lastImageBtn;
    private javax.swing.JButton nextImageBtn;
    private javax.swing.JTextField pathFld;
    private javax.swing.JButton previousImageBtn;
    // End of variables declaration//GEN-END:variables
}
