/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author anuja
 */
public class Calculator extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Calculator
     */
   
    int num1,num2;
    String operator;
    
     
    public Calculator() {
        initComponents();
        multiplyBtn.addActionListener(this);
	addBtn.addActionListener(this);
	divideBtn.addActionListener(this);
	subtractBtn.addActionListener(this);
	remainderBtn.addActionListener(this);
          resultFld.setEditable(false);
       
         
    }
    
   
       
        
    public void actionPerformed(ActionEvent e) {
              int result=0;
	     num1=Integer.parseInt(firstNumberFld.getText());
	     num2=Integer.parseInt(secondNumberFld.getText());
          //  String resultStr="zero not allowed";
           operator=e.getActionCommand();

	     switch(operator)
	     {
                  case "+":
	    	 result=num1+num2;
	    	 break;
                      
                  case "-":
	    	 result=num1-num2;
	    	 break;
                      
                      
                case "*":
                    result=num1*num2;
                    break;
	    
	        
                case "/":
                    int number=Integer.parseInt(secondNumberFld.getText());
                    if(number!=0)
                    {
                         result=num1/num2;
                    }
                   
                    break;


                case "%":
                    int number2=Integer.parseInt(secondNumberFld.getText());
                    if(number2!=0)
                    {
                         result=num1%num2;
                    }
                   
                    break;
               
	     }
             //   resultStr=String.valueOf(result);
		resultFld.setText(String.valueOf(result));
              
           }
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    	
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        enterFirstNumber = new javax.swing.JLabel();
        firstNumberFld = new javax.swing.JTextField();
        enterSecondNumber = new javax.swing.JLabel();
        secondNumberFld = new javax.swing.JTextField();
        resultFld = new javax.swing.JTextField();
        resultLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        subtractBtn = new javax.swing.JButton();
        multiplyBtn = new javax.swing.JButton();
        divideBtn = new javax.swing.JButton();
        remainderBtn = new javax.swing.JButton();

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.setText("Result");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterFirstNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterFirstNumber.setText("First Number");

        firstNumberFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                firstNumberFldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNumberFldKeyTyped(evt);
            }
        });

        enterSecondNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enterSecondNumber.setText("Second Number");

        secondNumberFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secondNumberFldKeyTyped(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resultLabel.setText("Result");

        addBtn.setText("+");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        subtractBtn.setText("-");
        subtractBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractBtnActionPerformed(evt);
            }
        });

        multiplyBtn.setText("*");
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });

        divideBtn.setText("/");
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });

        remainderBtn.setText("%");
        remainderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enterSecondNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterFirstNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtractBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNumberFld)
                            .addComponent(secondNumberFld)
                            .addComponent(resultFld, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(multiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(divideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(remainderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enterFirstNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstNumberFld, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resultFld, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtractBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
      // calc();
      //  int sum=num1+num2;
      //  resultFld.setText(String.valueOf(sum));
    }//GEN-LAST:event_addBtnActionPerformed

    private void subtractBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractBtnActionPerformed
  // calc();
   //int diffrence=num1-num2;
   // resultFld.setText(String.valueOf(diffrence));
    }//GEN-LAST:event_subtractBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
       // calc();
       // int product=num1*num2;
       //   resultFld.setText(String.valueOf(product));
        
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        //calc();
        //int divide=num1/num2;
        // resultFld.setText(String.valueOf(divide));
        
    }//GEN-LAST:event_divideBtnActionPerformed

    private void remainderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainderBtnActionPerformed
       // calc();
      //  int remainder=num1%num2;
        // resultFld.setText(String.valueOf(remainder));
        
    }//GEN-LAST:event_remainderBtnActionPerformed

    private void firstNumberFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNumberFldKeyPressed
      
       
    }//GEN-LAST:event_firstNumberFldKeyPressed

    private void firstNumberFldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNumberFldKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()<'0' || evt.getKeyChar()>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_firstNumberFldKeyTyped

    private void secondNumberFldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secondNumberFldKeyTyped
         if(evt.getKeyChar()<'0' || evt.getKeyChar()>'9')
        {
            evt.consume();
        }
    }//GEN-LAST:event_secondNumberFldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton divideBtn;
    private javax.swing.JLabel enterFirstNumber;
    private javax.swing.JLabel enterSecondNumber;
    private javax.swing.JTextField firstNumberFld;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton multiplyBtn;
    private javax.swing.JButton remainderBtn;
    private javax.swing.JTextField resultFld;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField secondNumberFld;
    private javax.swing.JButton subtractBtn;
    // End of variables declaration//GEN-END:variables
}
