/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author anuja
 */
public class ElementTransfer extends javax.swing.JFrame {

   private DefaultListModel leftModel=null;
   private DefaultListModel rightModel=null;
   
    public ElementTransfer() {
        initComponents();
        leftModel=new DefaultListModel();
        rightModel=new DefaultListModel();
        leftNameList.setModel(leftModel);
        rightNameList.setModel(rightModel);
        removeBtn.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameFld = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        leftNameList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        rightNameList = new javax.swing.JList();
        leftToRightSelectedBtn = new javax.swing.JButton();
        leftToRightAllBtn = new javax.swing.JButton();
        rightToLeftSelectedBtn = new javax.swing.JButton();
        rightToLeftAllBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFldKeyPressed(evt);
            }
        });

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        leftNameList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftNameListMouseClicked(evt);
            }
        });
        leftNameList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                leftNameListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(leftNameList);

        jScrollPane2.setViewportView(rightNameList);

        leftToRightSelectedBtn.setText(">");
        leftToRightSelectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftToRightSelectedBtnActionPerformed(evt);
            }
        });

        leftToRightAllBtn.setText(">>");
        leftToRightAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftToRightAllBtnActionPerformed(evt);
            }
        });

        rightToLeftSelectedBtn.setText("<");
        rightToLeftSelectedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightToLeftSelectedBtnActionPerformed(evt);
            }
        });

        rightToLeftAllBtn.setText("<<");
        rightToLeftAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightToLeftAllBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("REMOVE");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(leftToRightSelectedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(leftToRightAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(rightToLeftSelectedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rightToLeftAllBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(leftToRightSelectedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(leftToRightAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rightToLeftSelectedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rightToLeftAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        leftNameList.setModel(leftModel);
        String s=nameFld.getText().trim();
        if(!s.isEmpty()){
         leftModel.addElement(s);
        }
        nameFld.setText("");
        nameFld.requestFocus();
    }//GEN-LAST:event_addBtnActionPerformed
DefaultListModel model=new DefaultListModel();
    private void nameFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFldKeyPressed
       
        leftNameList.setModel(leftModel);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         String name = nameFld.getText().trim();
         if(!name.isEmpty()){
         leftModel.addElement(name);
         }
         nameFld.setText("");
        }
       
    
        
       
    }//GEN-LAST:event_nameFldKeyPressed

    private void leftToRightSelectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftToRightSelectedBtnActionPerformed
       
          /* int[] selectedName=leftNameList.getSelectedIndices();
       for(int j=selectedName.length-1;j>=0;j--){
      
      
              String name=(String)leftModel.get(j);
           rightModel.addElement(name);
            leftModel.remove(j);
       
       }*/
        selected(leftNameList,leftModel,rightModel);
       
    }//GEN-LAST:event_leftToRightSelectedBtnActionPerformed

    private void leftToRightAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftToRightAllBtnActionPerformed
     /*   for(int i = 0; i< leftModel.getSize();i++){
          rightModel.addElement(leftModel.getElementAt(i));
        }
         leftModel.removeAllElements();*/
        allTransfer(leftModel,rightModel);
    }//GEN-LAST:event_leftToRightAllBtnActionPerformed

    private void rightToLeftSelectedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightToLeftSelectedBtnActionPerformed
        /*int[] nameList=rightNameList.getSelectedIndices();
        for(int k=nameList.length-1;k>=0;k--)
        {
            
           String name=(String) rightModel.get(k);
           leftModel.addElement(name);
           rightModel.remove(k);
        }*/
        selected(rightNameList,rightModel,leftModel);
         
    }//GEN-LAST:event_rightToLeftSelectedBtnActionPerformed

    private void rightToLeftAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightToLeftAllBtnActionPerformed
        /* for(int i = 0; i< rightModel.getSize();i++){
          leftModel.addElement(rightModel.getElementAt(i));
        }
         rightModel.removeAllElements();*/
        allTransfer(rightModel,leftModel);
    }//GEN-LAST:event_rightToLeftAllBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
          int[] selectedIndex= leftNameList.getSelectedIndices();//{1,4}
          //System.out.println(Arrays.toString(selectedIndex));
     
              for(int i=selectedIndex.length-1;i>=0;i--)
           {
                leftModel.remove(selectedIndex[i]);
            }
        
       
         
        
     
        
    }//GEN-LAST:event_removeBtnActionPerformed

    private void leftNameListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftNameListMouseClicked
       
    }//GEN-LAST:event_leftNameListMouseClicked
   
    
    
    public void selected(JList nameList, DefaultListModel modelFirst, DefaultListModel modelSecond){
          int[] selectedName=nameList.getSelectedIndices();
       for(int j=selectedName.length-1;j>=0;j--){
      
      
              String name=(String)modelFirst.get(selectedName[j]);
           modelSecond.addElement(name);
            modelFirst.remove(selectedName[j]);
       } 
}
    
    public void allTransfer(DefaultListModel modelFirst,DefaultListModel modelSecond){
        for(int i = 0; i< modelFirst.getSize();i++){
          modelSecond.addElement(modelFirst.getElementAt(i));
        }
         modelFirst.removeAllElements();
    
}
    private void leftNameListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_leftNameListValueChanged
         int[] selectedIndex= leftNameList.getSelectedIndices();
        if(selectedIndex.length>=1) {
             removeBtn.setEnabled(true);
        } else {
           removeBtn.setEnabled(false);
        }
    }//GEN-LAST:event_leftNameListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElementTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElementTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElementTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElementTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElementTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList leftNameList;
    private javax.swing.JButton leftToRightAllBtn;
    private javax.swing.JButton leftToRightSelectedBtn;
    private javax.swing.JTextField nameFld;
    private javax.swing.JButton removeBtn;
    private javax.swing.JList rightNameList;
    private javax.swing.JButton rightToLeftAllBtn;
    private javax.swing.JButton rightToLeftSelectedBtn;
    // End of variables declaration//GEN-END:variables
}
