/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author anuja
 */
public class ImageDisplayNumber extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplayNumber
     */
    int i=0;
    File[] allFiles;
    //int j;
    File folder;
    public ImageDisplayNumber() {
        initComponents();
        imageNumberFld.setEditable(false);
        imageNameFld.setEditable(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathFld = new javax.swing.JTextField();
        folderChooseBtn = new javax.swing.JButton();
        imageDisplayLabel = new javax.swing.JLabel();
        firstImageBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        forwardBtn = new javax.swing.JButton();
        lastImageBtn = new javax.swing.JButton();
        imageNumberFld = new javax.swing.JTextField();
        imageNameFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pathFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathFldActionPerformed(evt);
            }
        });

        folderChooseBtn.setText("...");
        folderChooseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderChooseBtnActionPerformed(evt);
            }
        });

        firstImageBtn.setText("|<");
        firstImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstImageBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        forwardBtn.setText(">");
        forwardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardBtnActionPerformed(evt);
            }
        });

        lastImageBtn.setText(">|");
        lastImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastImageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imageDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pathFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(forwardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folderChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imageNameFld, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(imageNumberFld))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathFld, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folderChooseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(imageDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(imageNameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imageNumberFld, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstImageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(forwardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastImageBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pathFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathFldActionPerformed

    private void lastImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastImageBtnActionPerformed
       
             ImageIcon icon=new ImageIcon(allFiles[allFiles.length-1].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);
                 imageDisplayLabel.setIcon(scaledIcon);
                  imageNumberFld.setText(+allFiles.length+"/"+allFiles.length);
                   imageNameFld.setText(allFiles[allFiles.length-1].getName());
                 
    }//GEN-LAST:event_lastImageBtnActionPerformed

    private void forwardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardBtnActionPerformed
       
        if(i!=allFiles.length-1)
                  
                  i++;
                 ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);
                 imageDisplayLabel.setIcon(scaledIcon);
                imageNameFld.setText(allFiles[i].getName());
                imageNumberFld.setText(String.valueOf(i+1)+"/"+allFiles.length);
               
                
                
                
                 
    }//GEN-LAST:event_forwardBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
         
        if(i!=0)
        {
              i--;
             ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);
                 imageDisplayLabel.setIcon(scaledIcon);
                  imageNameFld.setText(allFiles[i].getName());
                 imageNumberFld.setText(String.valueOf(i+1)+"/"+allFiles.length);
               
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void folderChooseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderChooseBtnActionPerformed
      
        FileNameExtensionFilter fnef=new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        JFileChooser chooser=new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.addChoosableFileFilter(fnef);
        chooser.showOpenDialog(null);
          folder=chooser.getSelectedFile();
          if(folder!=null)
          {
              if(folder.isDirectory())
              {
                       allFiles=folder.listFiles();

                      String fileName=folder.getAbsolutePath();
                      pathFld.setText(fileName);
                      imageNumberFld.setText("1/"+allFiles.length);
                      imageNameFld.setText(allFiles[0].getName());


                       ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                        Image img=icon.getImage();
                        Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                        ImageIcon scaledIcon=new ImageIcon(imgScale);
                        imageDisplayLabel.setIcon(scaledIcon);
                }
            
             
       }
       
        
     
    }//GEN-LAST:event_folderChooseBtnActionPerformed

    private void firstImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstImageBtnActionPerformed
        
             ImageIcon icon=new ImageIcon(allFiles[0].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);
                 imageDisplayLabel.setIcon(scaledIcon);
                 imageNumberFld.setText("1/"+allFiles.length);
                  imageNameFld.setText(allFiles[0].getName());
                   
    }//GEN-LAST:event_firstImageBtnActionPerformed
    public void imageDisplay(int index){
     /*   ImageIcon icon=new ImageIcon(allFiles[index].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);*/
    }
    
     public void imageDisplayFile(ImageIcon f){
       /* ImageIcon icon=new ImageIcon(allFiles[i].getAbsolutePath());
                 Image img=icon.getImage();
                 Image imgScale=img.getScaledInstance(imageDisplayLabel.getWidth(), imageDisplayLabel.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon scaledIcon=new ImageIcon(imgScale);*/
                
                 //imageDisplayLabel.setIcon(scaledIcon[l]);
                 
   }
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageDisplayNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageDisplayNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageDisplayNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageDisplayNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageDisplayNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton firstImageBtn;
    private javax.swing.JButton folderChooseBtn;
    private javax.swing.JButton forwardBtn;
    private javax.swing.JLabel imageDisplayLabel;
    private javax.swing.JTextField imageNameFld;
    private javax.swing.JTextField imageNumberFld;
    private javax.swing.JButton lastImageBtn;
    private javax.swing.JTextField pathFld;
    // End of variables declaration//GEN-END:variables
}
