/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.quiz;

import javax.swing.JOptionPane;

/**
 *
 * @author anuja
 */
public class AddQuestionInternalFrame extends javax.swing.JInternalFrame {

   
   // int j;
 
    
    int id;
    int presentID;
    public AddQuestionInternalFrame() {
        initComponents();
        
      
       id= QuestionService.getLastQuestionID();
      System.out.println(id);
       presentID=(id+1);
       questnIDFld.setText(String.valueOf(id+1));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questnFld = new javax.swing.JTextField();
        questnLabel = new javax.swing.JLabel();
        closeBtn = new javax.swing.JButton();
        option1Label = new javax.swing.JLabel();
        option2Label = new javax.swing.JLabel();
        option3Fld = new javax.swing.JTextField();
        option4Fld = new javax.swing.JTextField();
        questnIDFld = new javax.swing.JTextField();
        addLabel = new javax.swing.JLabel();
        option3Label = new javax.swing.JLabel();
        option1Fld = new javax.swing.JTextField();
        option4Label = new javax.swing.JLabel();
        option2Fld = new javax.swing.JTextField();
        questnIDLabel = new javax.swing.JLabel();
        rightOptionDropDown = new javax.swing.JComboBox();
        rightOptionLabel = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        questnDescriptionArea = new javax.swing.JTextArea();

        questnFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questnFldActionPerformed(evt);
            }
        });

        questnLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questnLabel.setText("QUESTION");

        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        option1Label.setText("OPTION 1");

        option2Label.setText("OPTION 2");

        option3Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3FldActionPerformed(evt);
            }
        });

        questnIDFld.setEditable(false);
        questnIDFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questnIDFldActionPerformed(evt);
            }
        });

        addLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addLabel.setText("ADD QUESTION");

        option3Label.setText("OPTION 3");

        option1Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1FldActionPerformed(evt);
            }
        });

        option4Label.setText("OPTION 4");

        option2Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2FldActionPerformed(evt);
            }
        });

        questnIDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        questnIDLabel.setText("QUES. ID");

        rightOptionDropDown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "option 1", "option 2", "option 3", "option 4" }));
        rightOptionDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightOptionDropDownActionPerformed(evt);
            }
        });

        rightOptionLabel.setText("RIGHT OPTION");

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        questnDescriptionArea.setColumns(20);
        questnDescriptionArea.setRows(5);
        jScrollPane1.setViewportView(questnDescriptionArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questnIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questnIDFld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightOptionDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 135, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(addLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(option2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(option3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(option4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rightOptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questnIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questnIDFld, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option1Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option2Label)
                    .addComponent(option2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(option3Label)
                    .addComponent(option3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(option4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4Fld, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightOptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightOptionDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void option3FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option3FldActionPerformed

    private void questnIDFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questnIDFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questnIDFldActionPerformed

    private void questnFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questnFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questnFldActionPerformed

    private void option1FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1FldActionPerformed

    private void rightOptionDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightOptionDropDownActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rightOptionDropDownActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
  Question question=new Question();
  question.setQuestion(questnDescriptionArea.getText());
  question.setOption1(option1Fld.getText());
  question.setOption2(option2Fld.getText());
  question.setOption3(option3Fld.getText());
  question.setOption4(option4Fld.getText());
  switch((String)rightOptionDropDown.getModel().getSelectedItem()){
      case "option 1":
          question.setRightAnswer(question.getOption1());
          break;
          
      case "option 2":
          question.setRightAnswer(question.getOption2());
          break;
          
           case "option 3":
          question.setRightAnswer(question.getOption3());
          break;
               
                case "option 4":
          question.setRightAnswer(question.getOption4());
          break;
  }
       QuestionService.addQuestion(question);
        questnDescriptionArea.setText(" ");
        option1Fld.setText("");
        option2Fld.setText("");
        option3Fld.setText("");
        option4Fld.setText("");
        questnIDFld.setText(String.valueOf(presentID+1));
        rightOptionDropDown.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "Added in Database");
       
    }//GEN-LAST:event_addBtnActionPerformed

    private void option2FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2FldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addLabel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField option1Fld;
    private javax.swing.JLabel option1Label;
    private javax.swing.JTextField option2Fld;
    private javax.swing.JLabel option2Label;
    private javax.swing.JTextField option3Fld;
    private javax.swing.JLabel option3Label;
    private javax.swing.JTextField option4Fld;
    private javax.swing.JLabel option4Label;
    private javax.swing.JTextArea questnDescriptionArea;
    private javax.swing.JTextField questnFld;
    private javax.swing.JTextField questnIDFld;
    private javax.swing.JLabel questnIDLabel;
    private javax.swing.JLabel questnLabel;
    private javax.swing.JComboBox rightOptionDropDown;
    private javax.swing.JLabel rightOptionLabel;
    // End of variables declaration//GEN-END:variables
}
