/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.quiz;

import javax.swing.JOptionPane;
//import static project.quiz.SearchTableIF.questionTable;

/**
 *
 * @author anuja
 */
public class UpdateInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditInternalFrame
     */
    //SearchTableIF searchTable=new SearchTableIF();
    public UpdateInternalFrame() {
        initComponents();
         
          
             
                  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightAnswerFld = new javax.swing.JTextField();
        questionIDLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        option1Label = new javax.swing.JLabel();
        option2Label = new javax.swing.JLabel();
        option3Label = new javax.swing.JLabel();
        option4Label = new javax.swing.JLabel();
        rightOptionLabel = new javax.swing.JLabel();
        option1Fld = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionArea = new javax.swing.JTextArea();
        questionIDFld = new javax.swing.JTextField();
        option2Fld = new javax.swing.JTextField();
        option3Fld = new javax.swing.JTextField();
        option4Fld = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        rightOptionComboBox = new javax.swing.JComboBox();

        rightAnswerFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightAnswerFldActionPerformed(evt);
            }
        });

        questionIDLabel.setText("Question ID");

        questionLabel.setText("Question");

        option1Label.setText("Option 1");

        option2Label.setText("Option 2");

        option3Label.setText("Option 3");

        option4Label.setText("Option 4");

        rightOptionLabel.setText("Right Option");

        option1Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1FldActionPerformed(evt);
            }
        });

        questionArea.setColumns(20);
        questionArea.setRows(5);
        jScrollPane1.setViewportView(questionArea);

        option3Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option3FldActionPerformed(evt);
            }
        });

        option4Fld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option4FldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("          UPDATE");

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        rightOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Option1", "Option2", "Option3", "Option4" }));
        rightOptionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightOptionComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(questionIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(questionLabel)
                                .addComponent(option1Label)
                                .addComponent(option2Label)
                                .addComponent(option3Label)
                                .addComponent(option4Label)
                                .addComponent(rightOptionLabel)))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(option4Fld)
                            .addComponent(option3Fld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(option2Fld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(option1Fld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionIDFld, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBtn)
                            .addComponent(rightOptionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionIDFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionLabel)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option1Label)
                            .addComponent(option1Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option2Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option2Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option3Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option4Fld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightOptionLabel)
                    .addComponent(rightOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(updateBtn))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option1FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option1FldActionPerformed

    private void option3FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option3FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option3FldActionPerformed

    private void option4FldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option4FldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option4FldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void rightAnswerFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightAnswerFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightAnswerFldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String selectedData=null;
        Question questions=new Question();
        questions.setQuestionId(Integer.parseInt(questionIDFld.getText()));
        questions.setQuestion(questionArea.getText());
        questions.setOption1(option1Fld.getText());
        questions.setOption2(option2Fld.getText());
        questions.setOption3(option3Fld.getText());
        questions.setOption4(option4Fld.getText());
        questions.setRightAnswer((String) rightOptionComboBox.getSelectedItem());
       
           
        SearchTableIF searchTable=new SearchTableIF();
       
       searchTable.UpdatedTable(questions);
        
          this.dispose();
           int[] selectedRow = searchTable.questionTable.getSelectedRows();
            int[] selectedColumns = searchTable.questionTable.getSelectedColumns();
            for (int k = 0; k < selectedRow.length; k++) {
                for (int j = 0; j < selectedColumns.length; j++) {
                    
                        selectedData = (String)searchTable. questionTable.getValueAt(selectedRow[k], selectedColumns[j]);
                        System.out.println("Selected: " + selectedData);
            QuestionService.updateQuestion(questions);
                }
            }
              JOptionPane.showMessageDialog(this, "Record Updated");
           
       
       
       
       
    }//GEN-LAST:event_updateBtnActionPerformed
   //*******************//
    public  void questionToBeUpdated(Question questn){
        // SearchTableIF table=new SearchTableIF();
           //table.getValue();
           questionIDFld.setText(String.valueOf(questn.getQuestionId()));
           questionIDFld.setEditable(false);
           questionArea.setText(questn.getQuestion());
           option1Fld.setText(questn.getOption1());
           option2Fld.setText(questn.getOption2());
          option3Fld.setText(questn.getOption3());
             option4Fld.setText(questn.getOption4());
             if(questn.getRightAnswer().equals(questn.getOption1())){
                 rightOptionComboBox.setSelectedIndex(0);
             }
             else if(questn.getRightAnswer().equals(questn.getOption2())){
               rightOptionComboBox.setSelectedIndex(1);
             }
             else if(questn.getRightAnswer().equals(questn.getOption3())){
                  rightOptionComboBox.setSelectedIndex(2);
             }
              else if(questn.getRightAnswer().equals(questn.getOption4())){
                  rightOptionComboBox.setSelectedIndex(3);
             }
           
     }
    private void rightOptionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightOptionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightOptionComboBoxActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField option1Fld;
    private javax.swing.JLabel option1Label;
    public javax.swing.JTextField option2Fld;
    private javax.swing.JLabel option2Label;
    public javax.swing.JTextField option3Fld;
    private javax.swing.JLabel option3Label;
    public javax.swing.JTextField option4Fld;
    private javax.swing.JLabel option4Label;
    public javax.swing.JTextArea questionArea;
    public javax.swing.JTextField questionIDFld;
    private javax.swing.JLabel questionIDLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextField rightAnswerFld;
    public javax.swing.JComboBox rightOptionComboBox;
    private javax.swing.JLabel rightOptionLabel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
